


INSERT INTO Designation VALUES (1,'DIRECTOR',1);
INSERT INTO Designation VALUES (2,'MANAGER',10);
INSERT INTO Designation VALUES (3,'LEAD',20);
INSERT INTO Designation VALUES (4,'DEVELOPER',30);
INSERT INTO Designation VALUES (5,'DEVOPS',30);
INSERT INTO Designation VALUES (6,'QA',30);
INSERT INTO Designation VALUES (7,'INTERN',40);


INSERT INTO employee VALUES(1,'THOR',null,1);
INSERT INTO employee VALUES (2,'IRONMAN',1,2);
INSERT INTO employee VALUES (3,'HULK',1,3);
INSERT INTO employee VALUES (4,'CAPTAINAMERICA',1,2);
INSERT INTO employee VALUES (5,'WARMACHINE',2,6);
INSERT INTO employee VALUES (6,'VISION',2,5);
INSERT INTO employee VALUES (7,'SPIDERMAN',2,7);
INSERT INTO employee VALUES (8,'BLACKWIDOW',3,4);
INSERT INTO employee VALUES (9,'FALCON',4,4);
INSERT INTO employee VALUES (10,'ANTMAN',4,3);




